DATASET_CONFIG = {
    'analysis': {
        'table_name': 'analysis_results',
        'required_columns': [],
        'canonical_columns': {},
        'numeric_columns': [],
        'load_columns': [],
        'indicator_rules': [],
    },
    'boundaries': {
        'table_name': 'districts',
        'required_columns': ['code', 'name'],
        'canonical_columns': {
            'code': ['code', 'adm_code', 'gid', 'id_code', 'adm3_pcode', 'adm2_pcode', 'adm1_pcode'],
            'name': ['name', 'adm_name', 'district', 'ward', 'village', 'adm3_name', 'adm2_name', 'adm1_name', 'adm3_ref_n'],
            'type': ['type', 'adm_level', 'admin_type', 'boundary_type'],
            'parent_code': ['parent_code', 'district_code', 'ward_code', 'parentid', 'adm1_pcode'],
            'source': ['source'],
            'level': ['level', 'admin_level', 'adm_level_name'],
            'district_name': ['district_name', 'district'],
            'ward_name': ['ward_name', 'ward'],
            'village_name': ['village_name', 'village'],
            'valid_on': ['valid_on', 'date_valid', 'effective_date'],
            'boundary_version': ['boundary_version', 'version'],
            'reference_name': ['reference_name'],
        },
        'numeric_columns': [],
        'load_columns': [
            'code',
            'name',
            'type',
            'parent_id',
            'source',
            'valid_on',
            'boundary_version',
            'reference_name',
            'population_total',
            'population_density',
            'area_sq_km',
            'metadata',
            'centroid',
            'simplified_geom',
            'geom',
        ],
        'indicator_rules': [],
    },
    'education': {
        'table_name': 'education_facilities',
        'required_columns': ['name'],
        'canonical_columns': {
            'name': ['name', 'facility_name', 'school_name','school_nam'],
            'name:en': ['name_en', 'name:en', 'english_name'],
            'amenity': ['amenity'],
            'building': ['building'],
            'operator:type': ['operator_type', 'operator:type'],
            'capacity:persons': ['capacity_persons', 'capacity:persons', 'capacity'],
            'addr:full': ['addr_full', 'address', 'full_address', 'addr:full'],
            'addr:city': ['addr_city', 'city', 'addr:city'],
            'source': ['source'],
            'source_school_id': ['source_school_id', 'school_id'],
            'source_gid': ['source_gid', 'gid', 'objectid'],
            'status': ['status', 'school_status', 'operational_status'],
            'comments': ['comments', 'comment', 'notes', 'remarks'],
            'student_enrollment': ['student_enrollment', 'enrollment_total', 'enrollment', 'students_en', 'student_en', 'students_total', 'student_count'],
            'student_enrollment_total': ['student_enrollment_total', 'enrollment_total', 'enrollment', 'students_total', 'student_en', 'student_count'],
            'teacher_distribution': ['teacher_distribution', 'teacher_di'],
            'teacher_count': ['teacher_count', 'teachers_count', 'teachers', 'teacher_di'],
            'osm_id': ['osm_id'],
            'osm_type': ['osm_type'],
            'district_name': ['district', 'district_name'],
            'longitude': ['longitude', 'lon', 'lng', 'x_coord', 'x'],
            'latitude': ['latitude', 'lat', 'y_coord', 'y'],
            'coordinates': ['coordinates', 'coord', 'gps', 'location_coordinates'],
        },
        'numeric_columns': ['capacity:persons', 'student_enrollment_total', 'teacher_count', 'source_school_id', 'source_gid', 'osm_id', 'longitude', 'latitude'],
        'load_columns': [
            'name',
            'name:en',
            'amenity',
            'building',
            'operator:type',
            'capacity:persons',
            'addr:full',
            'addr:city',
            'source',
            'name:ny',
            'source_school_id',
            'source_gid',
            'status',
            'comments',
            'student_enrollment',
            'student_enrollment_total',
            'teacher_distribution',
            'teacher_count',
            'osm_id',
            'osm_type',
            'ta_id',
            'ward_id',
            'district_id',
            'geom',
        ],
        'indicator_rules': ['schools_per_1000_population', 'teachers_per_100_students', 'student_enrollment_total'],
    },
    'health': {
        'table_name': 'health_facilities',
        'required_columns': ['name'],
        'canonical_columns': {
            'code': ['code', 'facility_code', 'health_facility_code', 'hf_code'],
            'name': ['name', 'facility_name', 'health_facility_name'],
            'common_name': ['common_name', 'facility_common_name', 'short_name', 'alt_name'],
            'name:en': ['name_en', 'name:en', 'english_name'],
            'amenity': ['amenity'],
            'building': ['building'],
            'type': ['type', 'facility_type', 'health_facility_type'],
            'healthcare': ['healthcare'],
            'healthcare:speciality': ['healthcare_speciality', 'healthcare:speciality'],
            'ownership': ['ownership', 'owner', 'operator', 'operator_type', 'operator:type'],
            'operator:type': ['operator_type', 'operator:type'],
            'capacity:persons': ['capacity_persons', 'capacity:persons', 'capacity'],
            'addr:full': ['addr_full', 'address', 'full_address', 'addr:full'],
            'addr:city': ['addr_city', 'city', 'addr:city'],
            'zone': ['zone', 'health_zone', 'service_zone'],
            'source': ['source'],
            'name:ny': ['name_ny', 'name:ny'],
            'status': ['status', 'facility_status', 'operational_status'],
            'doctor_count': ['doctor_count', 'doctors_count', 'number_of_doctors', 'doctors'],
            'nurse_midwife_count': ['nurse_midwife_count', 'number_of_nurses_midwives', 'nurse_count', 'midwife_count', 'nurses_midwives'],
            'bed_capacity': ['bed_capacity', 'bed_capcity', 'bed_capacity_total', 'number_of_beds_capacity'],
            'beds_count': ['beds_count', 'beds', 'bed_count'],
            'patient_visits_total': ['patient_visits_total', 'patient_visits', 'visits_total', 'outpatient_visits'],
            'services_offered': ['services_offered', 'services', 'service_list'],
            'osm_id': ['osm_id'],
            'osm_type': ['osm_type'],
            'district_name': ['district', 'district_name'],
            'ward_name': ['ward', 'ward_name'],
            'village_name': ['village', 'village_name'],
            'longitude': ['longitude', 'lon', 'lng', 'x_coord', 'x'],
            'latitude': ['latitude', 'lat', 'y_coord', 'y'],
            'coordinates': ['coordinates', 'coord', 'gps', 'location_coordinates'],
        },
        'numeric_columns': ['capacity:persons', 'doctor_count', 'nurse_midwife_count', 'bed_capacity', 'beds_count', 'patient_visits_total', 'osm_id', 'longitude', 'latitude'],
        'load_columns': [
            'code',
            'name',
            'common_name',
            'name:en',
            'amenity',
            'building',
            'type',
            'healthcare',
            'healthcare:speciality',
            'ownership',
            'operator:type',
            'capacity:persons',
            'addr:full',
            'addr:city',
            'zone',
            'district_name',
            'source',
            'name:ny',
            'status',
            'doctor_count',
            'nurse_midwife_count',
            'bed_capacity',
            'beds_count',
            'latitude',
            'longitude',
            'patient_visits_total',
            'services_offered',
            'osm_id',
            'osm_type',
            'ward_id',
            'district_id',
            'geom',
        ],
        'indicator_rules': ['health_facilities_per_1000_population', 'beds_per_1000_population', 'patient_visits_total'],
    },
    'welfare': {
        'table_name': 'welfare_beneficiaries',
        'required_columns': ['program_name'],
        'canonical_columns': {
            'program_name': ['program_name', 'programme_name', 'program'],
            'beneficiary_count': ['beneficiary_count', 'beneficiaries', 'count'],
            'district_name': ['district', 'district_name'],
            'ward_name': ['ward', 'ward_name'],
            'village_name': ['village', 'village_name'],
            'longitude': ['longitude', 'lon', 'lng', 'x_coord', 'x'],
            'latitude': ['latitude', 'lat', 'y_coord', 'y'],
            'coordinates': ['coordinates', 'coord', 'gps', 'location_coordinates'],
        },
        'numeric_columns': ['beneficiary_count', 'longitude', 'latitude'],
        'load_columns': ['program_name', 'beneficiary_count', 'ta_id', 'ward_id', 'geom'],
        'indicator_rules': ['beneficiaries_per_1000_population'],
    },
    'disaster': {
        'table_name': 'disaster_zones',
        'required_columns': ['event_type', 'risk_level'],
        'canonical_columns': {
            'event_type': ['event_type', 'hazard_type', 'disaster_type'],
            'risk_level': ['risk_level', 'risk', 'severity'],
            'population_at_risk': ['population_at_risk', 'people_at_risk'],
            'district_name': ['district', 'district_name'],
            'ward_name': ['ward', 'ward_name'],
            'village_name': ['village', 'village_name'],
        },
        'numeric_columns': ['population_at_risk'],
        'load_columns': ['event_type', 'risk_level', 'population_at_risk', 'geom'],
        'indicator_rules': ['population_at_risk_total'],
    },
    'worldpop': {
        'table_name': 'districts',
        'required_columns': [],
        'canonical_columns': {},
        'numeric_columns': [],
        'load_columns': [],
        'indicator_rules': ['population_total', 'population_density'],
    },
}

MISSING_VALUE_TOKENS = {
    '',
    '-',
    '--',
    '---',
    'na',
    'n/a',
    'n\\a',
    'null',
    'none',
    'unknown',
    'nan',
    'nil',
    'missing',
    'not available',
    'not_applicable',
    'not applicable',
}

GEOGRAPHIC_COLUMNS = ['district_name', 'ward_name', 'village_name']
