DATASET_CONFIG = {
    'analysis': {
        'table_name': 'analysis_results',
        'required_columns': [],
        'canonical_columns': {},
        'numeric_columns': [],
        'load_columns': [],
        'indicator_rules': [],
    },
    'boundaries': {
        'table_name': 'districts',
        'required_columns': ['code', 'name'],
        'canonical_columns': {
            'code': ['code', 'adm_code', 'gid', 'id_code', 'adm3_pcode', 'adm2_pcode', 'adm1_pcode'],
            'name': ['name', 'adm_name', 'district', 'ward', 'village', 'adm3_name', 'adm2_name', 'adm1_name', 'adm3_ref_n'],
            'type': ['type', 'adm_level', 'admin_type', 'boundary_type'],
            'parent_code': ['parent_code', 'district_code', 'ward_code', 'parentid', 'adm1_pcode'],
            'level': ['level', 'admin_level', 'adm_level_name'],
            'district_name': ['district_name', 'district'],
            'ward_name': ['ward_name', 'ward'],
            'village_name': ['village_name', 'village'],
            'valid_on': ['valid_on', 'date_valid', 'effective_date'],
            'boundary_version': ['boundary_version', 'version'],
            'reference_name': ['reference_name'],
        },
        'numeric_columns': [],
        'load_columns': [
            'code',
            'name',
            'type',
            'parent_id',
            'valid_on',
            'boundary_version',
            'reference_name',
            'population_total',
            'population_density',
            'area_sq_km',
            'metadata',
            'centroid',
            'simplified_geom',
            'geom',
        ],
        'indicator_rules': [],
    },
    'education': {
        'table_name': 'education_facilities',
        'required_columns': ['school_name'],
        'canonical_columns': {
            'school_name': ['school_name', 'schoolname', 'name', 'facility_name', 'school_nam'],
            'status': ['status', 'school_status', 'operational_status'],
            'operator': ['operator', 'operator_name', 'ownership', 'owner', 'management_authority'],
            'student_enrollment': ['student_enrollment', 'enrollment_total', 'enrollment', 'students_en', 'student_en', 'students_total', 'student_count'],
            'student_enrollment_total': ['student_enrollment_total', 'enrollment_total', 'enrollment', 'students_total', 'student_en', 'student_count', 'number_of_students'],
            'student_classroom_ratio': ['student_classroom_ratio', 'students_classroom_ratio', 'student_to_classroom_ratio', 'student_class_ratio'],
            'special_needs_students': ['special_needs_students', 'special_needs_student_count', 'number_of_special_needs_student', 'special_needs_count', 'special_needs_student'],
            'teacher_distribution': ['teacher_distribution', 'teacher_di'],
            'teacher_count': ['teacher_count', 'teachers_count', 'teachers', 'teacher_di'],
            'blocks_count': ['blocks_count', 'number_of_blocks', 'block_count'],
            'water_equipment_facility_count': ['water_equipment_facility_count', 'number_of_water_equipment_facility', 'water_facility_count', 'water_facility_equipment_count'],
            'toilets_count': ['toilets_count', 'number_of_toilets', 'toilet_count'],
            'classroom_pressure': ['classroom_pressure', 'class_pressure'],
            'teacher_pressure': ['teacher_pressure'],
            'district': ['district', 'district_name'],
            'district_name': ['district', 'district_name'],
            'x_coordinate': ['x_coordinate', 'x-cordinate', 'x_coord', 'xcoord', 'x', 'longitude', 'lon', 'lng'],
            'y_coordinate': ['y_coordinate', 'y-cordinate', 'y_coord', 'ycoord', 'y', 'latitude', 'lat'],
            'longitude': ['longitude', 'lon', 'lng', 'x_coord', 'x'],
            'latitude': ['latitude', 'lat', 'y_coord', 'y'],
            'coordinates': ['coordinates', 'coord', 'gps', 'location_coordinates'],
        },
        'numeric_columns': [
            'student_enrollment_total',
            'student_classroom_ratio',
            'special_needs_students',
            'teacher_count',
            'blocks_count',
            'water_equipment_facility_count',
            'toilets_count',
            'classroom_pressure',
            'teacher_pressure',
            'x_coordinate',
            'y_coordinate',
            'longitude',
            'latitude',
        ],
        'load_columns': [
            'school_name',
            'status',
            'operator',
            'student_enrollment_total',
            'student_classroom_ratio',
            'special_needs_students',
            'teacher_distribution',
            'teacher_count',
            'blocks_count',
            'water_equipment_facility_count',
            'toilets_count',
            'classroom_pressure',
            'teacher_pressure',
            'district',
            'x_coordinate',
            'y_coordinate',
            'ta_id',
            'district_id',
            'geom',
        ],
        'indicator_rules': ['schools_per_1000_population', 'teachers_per_100_students', 'student_enrollment_total'],
    },
    'health': {
        'table_name': 'health_facilities',
        'required_columns': ['name'],
        'canonical_columns': {
            'code': ['code', 'facility_code', 'health_facility_code', 'hf_code'],
            'name': ['name', 'facility_name', 'health_facility_name'],
            'common_name': ['common_name', 'facility_common_name', 'short_name', 'alt_name'],
            'type': ['type', 'facility_type', 'health_facility_type'],
            'ownership': ['ownership', 'owner', 'operator', 'operator_type', 'operator:type'],
            'capacity:persons': ['capacity_persons', 'capacity:persons', 'capacity'],
            'zone': ['zone', 'health_zone', 'service_zone'],
            'source': ['source'],
            'status': ['status', 'facility_status', 'operational_status'],
            'doctor_count': ['doctor_count', 'doctors_count', 'number_of_doctors', 'doctors'],
            'nurse_midwife_count': ['nurse_midwife_count','nurse_midwives_total', 'number_of_nurses_midwives', 'nurse_count', 'midwife_count', 'nurses_midwives'],
            'bed_capacity': ['bed_capacity', 'bed_capcity', 'bed_capacity_total', 'number_of_beds_capacity'],
            'beds_count': ['beds_count', 'beds', 'bed_count'],
            'patient_visits_total': ['patient_visits_total', 'patient_visits', 'visits_total', 'outpatient_visits'],
            'services_offered': ['services_offered', 'services', 'service_list'],
            'district_name': ['district', 'district_name'],
            'ward_name': ['ward', 'ward_name'],
            'longitude': ['longitude', 'lon', 'lng', 'x_coord', 'x'],
            'latitude': ['latitude', 'lat', 'y_coord', 'y'],
            'coordinates': ['coordinates', 'coord', 'gps', 'location_coordinates'],
        },
        'numeric_columns': ['capacity:persons', 'doctor_count', 'nurse_midwife_count', 'bed_capacity', 'beds_count', 'patient_visits_total', 'longitude', 'latitude'],
        'load_columns': [
            'code',
            'name',
            'common_name',
            'type',
            'ownership',
            'capacity:persons',
            'zone',
            'district',
            'status',
            'doctor_count',
            'nurse_midwife_count',
            'bed_capacity',
            'beds_count',
            'latitude',
            'longitude',
            'patient_visits_total',
            'services_offered',
            'ta_id',
            'district_id',
            'geom',
        ],
        'indicator_rules': ['health_facilities_per_1000_population', 'beds_per_1000_population', 'patient_visits_total'],
    },
    'welfare': {
        'table_name': 'welfare_beneficiaries',
        'required_columns': ['program_name'],
        'canonical_columns': {
            'program_name': ['program_name', 'programme_name', 'program'],
            'beneficiary_count': ['beneficiary_count', 'beneficiaries', 'count'],
            'district_name': ['district', 'district_name'],
            'ward_name': ['ward', 'ward_name'],
            'village_name': ['village', 'village_name'],
            'longitude': ['longitude', 'lon', 'lng', 'x_coord', 'x'],
            'latitude': ['latitude', 'lat', 'y_coord', 'y'],
            'coordinates': ['coordinates', 'coord', 'gps', 'location_coordinates'],
        },
        'numeric_columns': ['beneficiary_count', 'longitude', 'latitude'],
        'load_columns': ['program_name', 'beneficiary_count', 'ta_id', 'ward_id', 'geom'],
        'indicator_rules': ['beneficiaries_per_1000_population'],
    },
    'disaster': {
        'table_name': 'disaster_zones',
        'required_columns': ['event_type', 'risk_level'],
        'canonical_columns': {
            'event_type': ['event_type', 'hazard_type', 'disaster_type'],
            'risk_level': ['risk_level', 'risk', 'severity'],
            'population_at_risk': ['population_at_risk', 'people_at_risk'],
            'district_name': ['district', 'district_name'],
            'ward_name': ['ward', 'ward_name'],
            'village_name': ['village', 'village_name'],
        },
        'numeric_columns': ['population_at_risk'],
        'load_columns': ['event_type', 'risk_level', 'population_at_risk', 'geom'],
        'indicator_rules': ['population_at_risk_total'],
    },
    'worldpop': {
        'table_name': 'districts',
        'required_columns': [],
        'canonical_columns': {},
        'numeric_columns': [],
        'load_columns': [],
        'indicator_rules': ['population_total', 'population_density'],
    },
}

MISSING_VALUE_TOKENS = {
    '',
    '-',
    '--',
    '---',
    'na',
    'n/a',
    'n\\a',
    'null',
    'none',
    'unknown',
    'nan',
    'nil',
    'missing',
    'not available',
    'not_applicable',
    'not applicable',
}

GEOGRAPHIC_COLUMNS = ['district_name', 'ward_name', 'village_name']
